# Gradient descent (Linear Regression)

Objective: minimise the cost function with the best fit regression line

y = mx+b

cost function = MSE

MSE = $\frac{\sum(y- \hat y)^2}{n}$

y = Actual values

$\hat y$ = Predicted values

n = total number of values

In [16]:
import numpy as np
import matplotlib.pyplot as plt

def Gradient_Descent(X,y):
    m = b = 0
    iteration = 1000
    learning_rate = 0.001
    n = len(X)
    
    
    for i in range(iteration):
        y_pred = m * X + b
        cost = (1/n)*sum([val**2 for val in (y-y_pred)])
        md = -(2/n) * sum(X*(y - y_pred))
        bd = -(2/n) * sum(y - y_pred)
        m = m - learning_rate * md
        b = b - learning_rate * bd
        

    #plt.scatter(m_arr, b_arr)
        
        print("M:{}, B:{}, iter:{}, cost:{} pred:{}".format(m,b,i,cost, y_pred))
    
    


X = np.array([[1,2,4],[4,5,8]])
y = np.array([[2],[4]])


Gradient_Descent(X,y)

M:[0.018 0.024 0.04 ], B:[0.006 0.006 0.006], iter:0, cost:[10. 10. 10.] pred:[[0 0 0]
 [0 0 0]]
M:[0.035664 0.047262 0.076728], B:[0.011898 0.01182  0.011508], iter:1, cost:[9.64333  9.397396 8.430916] pred:[[0.024 0.054 0.166]
 [0.078 0.126 0.326]]
M:[0.05299822 0.06980866 0.11045166], B:[0.01769588 0.01746553 0.01656425], iter:2, cost:[9.29973454 8.83123077 7.1080477 ] pred:[[0.047562 0.106344 0.31842 ]
 [0.154554 0.24813  0.625332]]
M:[0.07000877 0.09166195 0.14141676], B:[0.0233955  0.02294193 0.0212057 ], iter:3, cost:[8.96873399 8.29930083 5.99275971] pred:[[0.07069411 0.15708285 0.4583709 ]
 [0.22968877 0.36650884 0.90017756]]
M:[0.08670165 0.11284316 0.16984895], B:[0.02899867 0.02825442 0.02546629], iter:4, cost:[8.64986632 7.79953594 5.05247918] pred:[[0.09340427 0.20626584 0.58687274]
 [0.30343059 0.48125169 1.15253978]]
M:[0.10308272 0.13337293 0.19595544], B:[0.03450716 0.03340801 0.02937717], iter:5, cost:[8.34268645 7.32999105 4.25974449] pred:[[0.11570031 0.25394074 0.

M:[0.9202545  0.77387294 0.48932712], B:[0.37345161 0.21461338 0.07097784], iter:179, cost:[0.25158486 0.0317898  0.00050401] pred:[[1.29255028 1.76208857 2.02829183]
 [4.0518132  4.08353292 3.98559194]]
M:[0.92074292 0.77392833 0.48932922], B:[0.37410344 0.21476704 0.07096396], iter:180, cost:[0.250909   0.03176272 0.00050381] pred:[[1.29370612 1.76235927 2.02828634]
 [4.05446963 4.08397809 3.98559483]]
M:[0.92121977 0.77398104 0.48933131], B:[0.37475151 0.21492001 0.07095008], iter:181, cost:[0.25024962 0.03173617 0.00050362] pred:[[1.29484635 1.76262371 2.02828084]
 [4.05707511 4.08440871 3.98559772]]
M:[0.92168528 0.77403115 0.48933341], B:[0.37539591 0.21507231 0.07093621], iter:182, cost:[0.24960612 0.03171011 0.00050342] pred:[[1.29597129 1.7628821  2.02827534]
 [4.0596306  4.08482522 3.9856006 ]]
M:[0.92213965 0.77407874 0.4893355 ], B:[0.37603669 0.21522394 0.07092234], iter:183, cost:[0.24897793 0.03168452 0.00050322] pred:[[1.29708119 1.76313461 2.02826984]
 [4.06213703 4.08

 [4.17660358 4.09477748 3.98598479]]
M:[0.93261421 0.77220599 0.4896196 ], B:[0.44635611 0.23370337 0.06903349], iter:321, cost:[0.20867531 0.02912067 0.00047677] pred:[[1.37861109 1.7780479  2.02751726]
 [4.17671006 4.09475548 3.98598753]]
M:[0.93252799 0.77217609 0.48962163], B:[0.44680032 0.23383052 0.06901999], iter:322, cost:[0.20847034 0.0291036  0.00047659] pred:[[1.37897031 1.77811535 2.02751188]
 [4.17681294 4.09473331 3.98599027]]
M:[0.93244101 0.77214617 0.48962366], B:[0.44724408 0.23395763 0.06900649], iter:323, cost:[0.20826565 0.02908654 0.0004764 ] pred:[[1.37932831 1.7781827  2.0275065 ]
 [4.17691227 4.09471098 3.98599301]]
M:[0.93235329 0.77211623 0.48962569], B:[0.44768739 0.23408469 0.06899299], iter:324, cost:[0.20806123 0.02906949 0.00047622] pred:[[1.37968509 1.77824997 2.02750112]
 [4.17700811 4.09468848 3.98599575]]
M:[0.93226485 0.77208627 0.48962772], B:[0.44813025 0.23421171 0.0689795 ], iter:325, cost:[0.20785708 0.02905245 0.00047603] pred:[[1.38004068 1.7

M:[0.91527195 0.7675207  0.48993157], B:[0.51177916 0.25306448 0.06695876], iter:477, cost:[0.17925095 0.02657548 0.00044855] pred:[[1.42676935 1.78804374 2.02669026]
 [4.1729408  4.09069453 3.98640866]]
M:[0.91515343 0.76749115 0.48993354], B:[0.51217924 0.2531857  0.06694567], iter:478, cost:[0.17907671 0.0265599  0.00044837] pred:[[1.42705111 1.78810588 2.02668504]
 [4.17286695 4.09066799 3.98641132]]
M:[0.91503493 0.76746161 0.48993551], B:[0.51257912 0.25330689 0.06693257], iter:479, cost:[0.17890264 0.02654433 0.0004482 ] pred:[[1.42733267 1.788168   2.02667982]
 [4.17279296 4.09064145 3.98641398]]
M:[0.91491644 0.76743207 0.48993748], B:[0.51297878 0.25342805 0.06691948], iter:480, cost:[0.17872874 0.02652878 0.00044802] pred:[[1.42761404 1.78823011 2.0266746 ]
 [4.17271882 4.09061493 3.98641664]]
M:[0.91479796 0.76740255 0.48993944], B:[0.51337824 0.25354917 0.06690639], iter:481, cost:[0.17855501 0.02651323 0.00044785] pred:[[1.42789522 1.78829219 2.02666939]
 [4.17264453 4.09

 [4.15818047 4.08578264 3.98690452]]
M:[0.89333753 0.76202939 0.4903008 ], B:[0.58467718 0.27558541 0.06450327], iter:668, cost:[0.14886533 0.02376017 0.00041625] pred:[[1.47776075 1.79958545 2.02571148]
 [4.15810387 4.0857575  3.98690708]]
M:[0.89322741 0.76200144 0.49030269], B:[0.58504113 0.27570003 0.06449065], iter:669, cost:[0.14872064 0.02374624 0.00041609] pred:[[1.47801471 1.79964419 2.02570645]
 [4.1580273  4.08573236 3.98690964]]
M:[0.89311734 0.7619735  0.49030459], B:[0.58540492 0.27581462 0.06447804], iter:670, cost:[0.14857608 0.02373233 0.00041593] pred:[[1.47826854 1.79970291 2.02570143]
 [4.15795076 4.08570724 3.9869122 ]]
M:[0.89300732 0.76194557 0.49030649], B:[0.58576852 0.27592917 0.06446543], iter:671, cost:[0.14843166 0.02371842 0.00041576] pred:[[1.47852225 1.79976162 2.0256964 ]
 [4.15787426 4.08568212 3.98691476]]
M:[0.89289735 0.76191764 0.49030838], B:[0.58613195 0.2760437  0.06445282], iter:672, cost:[0.14828739 0.02370452 0.0004156 ] pred:[[1.47877583 1.7

M:[0.87374019 0.7569691  0.49064734], B:[0.64941553 0.29633761 0.06219862], iter:854, cost:[0.12423325 0.02130547 0.00038704] pred:[[1.5229238  1.81022018 2.02479283]
 [4.14444651 4.08120689 3.98737488]]
M:[0.87363953 0.75694263 0.49064917], B:[0.649748   0.29644615 0.06218646], iter:855, cost:[0.12411249 0.02129298 0.00038689] pred:[[1.52315572 1.8102758  2.02478799]
 [4.1443763  4.08118309 3.98737735]]
M:[0.87353892 0.75691617 0.490651  ], B:[0.6500803  0.29655466 0.06217429], iter:856, cost:[0.12399185 0.0212805  0.00038674] pred:[[1.52338753 1.81033141 2.02478314]
 [4.14430612 4.0811593  3.98737982]]
M:[0.87343836 0.75688972 0.49065283], B:[0.65041245 0.29666314 0.06216213], iter:857, cost:[0.12387133 0.02126803 0.00038659] pred:[[1.52361922 1.810387   2.02477829]
 [4.14423598 4.08113551 3.98738229]]
M:[0.87333784 0.75686327 0.49065466], B:[0.65074443 0.29677158 0.06214998], iter:858, cost:[0.12375093 0.02125557 0.00038643] pred:[[1.5238508  1.81044258 2.02477344]
 [4.14416588 4.08

In [5]:
def SGD(X,y):
    m,b = np.random.rand(2,1)
    iteration = 100
    learning_rate = 0.001
    n = len(X)
    
    m_arr = []
    b_arr = []
    
    for i in range(iteration):
        y_pred = m * X + b
        cost = (1/n)*sum([val**2 for val in (y-y_pred)])
        md = -(2/n) * sum(X*(y - y_pred))
        bd = -(2/n) * sum(y - y_pred)
        m = m - learning_rate * md
        b = b - learning_rate * bd
        
        m_arr.append(m)
        b_arr.append(b)
        
    #plt.scatter(m_arr, b_arr)
        
    
        
    print("M:{}, B:{}, iter:{}, cost:{} pred:{}".format(m,b,i,cost, y_pred))
    
    
        
