In [17]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_boston

In [18]:
df = load_boston()

In [19]:
dataset = pd.DataFrame(df.data,columns=df.feature_names)

In [20]:
dataset.head(5)

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [21]:
X = df.data
y = df.target


In [22]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state = 0)


In [23]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test= scaler.fit_transform(X_test)

In [41]:
def Gradient_Descent(X,y):
    m = b = 0
    iteration = 2000
    learning_rate = 0.03
    n = len(X)
    
    
    for i in range(iteration):
        y_pred = m * X + b
        cost = (1/n)*sum([val**2 for val in (y-y_pred)])
        md = -(2/n) * sum(X*(y - y_pred))
        bd = -(2/n) * sum(y - y_pred)
        m = m - learning_rate * md
        b = b - learning_rate * bd
        

    #plt.scatter(m_arr, b_arr)
        
        print("Prediction:{}, M(SLOPE):{}, B(Y-INTERCEPT):{}, COST:{}".format(y_pred, m , b, cost))


In [42]:
y_train = y_train.reshape(-1 ,1)

In [43]:
Gradient_Descent(X_train, y_train)

Prediction:[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], M(SLOPE):[-0.21443425  0.21329233 -0.27861191  0.08970788 -0.23570622  0.39164359
 -0.21595851  0.13568971 -0.21518011 -0.26588319 -0.31196208  0.17922112
 -0.41059704], B(Y-INTERCEPT):[1.36472881 1.36472881 1.36472881 1.36472881 1.36472881 1.36472881
 1.36472881 1.36472881 1.36472881 1.36472881 1.36472881 1.36472881
 1.36472881], COST:[602.12138418 602.12138418 602.12138418 602.12138418 602.12138418
 602.12138418 602.12138418 602.12138418 602.12138418 602.12138418
 602.12138418 602.12138418 602.12138418]
Prediction:[[1.40919308 1.25808708 0.93343317 ... 0.98187108 1.44081587 0.08856337]
 [1.44811477 1.4386931  1.52903943 ... 1.34695838 1.43674938 1.63836314]
 [1.43672187 1.25808708 0.93343317 ... 0.98187108 1.4361415  1.10220677]
 ...
 [1.44717954 1.25808708 1.40736501 ... 1.45929293 1.43580612 1.48907583]
 [1.44516693 

Prediction:[[21.24949107 18.97093481 14.07541672 ... 14.80582112 21.72633718
   1.33546399]
 [21.83639865 21.69432754 23.05667697 ... 20.31104208 21.66501775
  24.70519006]
 [21.66460286 18.97093481 14.07541672 ... 14.80582112 21.65585144
  16.62038603]
 ...
 [21.82229619 18.97093481 21.22192521 ... 22.00495622 21.65079417
  22.45405828]
 [21.79194759 18.97093481 23.08675486 ... 21.79321695 21.59484809
  15.00868078]
 [21.82688588 18.97093481 24.80721061 ... 24.54582743 21.72633718
  18.60873978]], M(SLOPE):[-3.25391947  3.23659147 -4.22777942  1.36126674 -3.57670967  5.9429719
 -3.27704926  2.05901519 -3.26523744 -4.03462822 -4.73384957  2.71957997
 -6.23057976], B(Y-INTERCEPT):[20.70899436 20.70899436 20.70899436 20.70899436 20.70899436 20.70899436
 20.70899436 20.70899436 20.70899436 20.70899436 20.70899436 20.70899436
 20.70899436], COST:[76.80121201 76.93565606 68.0913574  87.24298722 74.16551657 47.23780365
 76.62063464 84.39016333 76.71301094 69.99909312 62.66995238 80.61678958


Prediction:[[23.23001285 20.73908773 15.38729141 ... 16.18577188 23.75130257
   1.45993359]
 [23.87162213 23.71630952 25.20563436 ... 22.20409736 23.68426797
  27.00779425]
 [23.68381441 20.73908773 15.38729141 ... 16.18577188 23.67424733
  18.16946014]
 ...
 [23.85620527 20.73908773 23.19987776 ... 24.05588981 23.6687187
  24.54684965]
 [23.82302808 20.73908773 25.23851561 ... 23.82441576 23.60755827
  16.40753872]
 [23.86122274 20.73908773 27.11932344 ... 26.8335785  23.75130257
  20.34313494]], M(SLOPE):[-3.5372094   3.5183728  -4.5958547   1.47978017 -3.88810208  6.46037378
 -3.56235288  2.23827539 -3.54951271 -4.38588753 -5.14598388  2.95634969
 -6.77302111], B(Y-INTERCEPT):[22.51194291 22.51194291 22.51194291 22.51194291 22.51194291 22.51194291
 22.51194291 22.51194291 22.51194291 22.51194291 22.51194291 22.51194291
 22.51194291], COST:[72.05497082 72.19062957 63.26642311 82.59108695 69.39546201 42.22445856
 71.87276194 79.71248794 71.96597286 65.19139513 57.79603598 75.90502195


Prediction:[[23.46211643 20.94630314 15.54103413 ... 16.34749265 23.98861464
   1.47452057]
 [24.11013638 23.95327196 25.45747744 ... 22.42595047 23.92091026
  27.27764368]
 [23.92045217 20.94630314 15.54103413 ... 16.34749265 23.9107895
  18.35100102]
 ...
 [24.09456548 20.94630314 23.43168025 ... 24.29624518 23.90520564
  24.79211046]
 [24.0610568  20.94630314 25.49068723 ... 24.06245834 23.84343411
  16.57147528]
 [24.09963309 20.94630314 27.39028722 ... 27.10168725 23.98861464
  20.54639417]], M(SLOPE):[-3.57040903  3.55139564 -4.6389906   1.49366913 -3.92459513  6.52100974
 -3.59578851  2.25928346 -3.58282783 -4.42705272 -5.1942832   2.98409747
 -6.83659152], B(Y-INTERCEPT):[22.72323613 22.72323613 22.72323613 22.72323613 22.72323613 22.72323613
 22.72323613 22.72323613 22.72323613 22.72323613 22.72323613 22.72323613
 22.72323613], COST:[71.99229635 72.12797114 63.20270949 82.52965825 69.33247308 42.15825696
 71.81006593 79.65071888 71.90328786 65.12790911 57.73167555 75.8428027
 

Prediction:[[23.48422397 20.96604011 15.55567791 ... 16.36289632 24.01121828
   1.47590996]
 [24.13285452 23.97584229 25.48146513 ... 22.44708166 23.9434501
  27.30334645]
 [23.94299158 20.96604011 15.55567791 ... 16.36289632 23.9333198
  18.36829252]
 ...
 [24.11726895 20.96604011 23.4537591  ... 24.31913868 23.92773068
  24.8154712 ]
 [24.08372869 20.96604011 25.51470622 ... 24.08513155 23.86590095
  16.58709001]
 [24.12234133 20.96604011 27.41609613 ... 27.12722422 24.01121828
  20.56575432]], M(SLOPE):[-3.57357125  3.55454102 -4.64309923  1.49499203 -3.92807105  6.52678523
 -3.59897321  2.26128445 -3.58600105 -4.43097364 -5.19888364  2.98674041
 -6.84264651], B(Y-INTERCEPT):[22.74336151 22.74336151 22.74336151 22.74336151 22.74336151 22.74336151
 22.74336151 22.74336151 22.74336151 22.74336151 22.74336151 22.74336151
 22.74336151], COST:[71.99172775 72.12740268 63.20213146 82.52910095 69.33190163 42.15765636
 71.80949713 79.65015849 71.90271917 65.12733315 57.73109165 75.84223823
 

Prediction:[[23.48632968 20.96792003 15.55707271 ... 16.3643635  24.01337124
   1.4760423 ]
 [24.13501839 23.97799208 25.48374993 ... 22.44909437 23.94559699
  27.3057946 ]
 [23.94513842 20.96792003 15.55707271 ... 16.3643635  23.93546578
  18.36993951]
 ...
 [24.11943142 20.96792003 23.45586208 ... 24.32131926 23.92987615
  24.81769627]
 [24.08588816 20.96792003 25.51699399 ... 24.08729114 23.86804088
  16.58857729]
 [24.12450426 20.96792003 27.4185544  ... 27.12965658 24.01337124
  20.56759835]], M(SLOPE):[-3.57387245  3.55484061 -4.64349057  1.49511804 -3.92840212  6.52733533
 -3.59927655  2.26147504 -3.58630329 -4.4313471  -5.19932183  2.98699215
 -6.84322324], B(Y-INTERCEPT):[22.74527842 22.74527842 22.74527842 22.74527842 22.74527842 22.74527842
 22.74527842 22.74527842 22.74527842 22.74527842 22.74527842 22.74527842
 22.74527842], COST:[71.99172259 72.12739752 63.20212622 82.5290959  69.33189644 42.15765091
 71.80949197 79.65015341 71.90271401 65.12732792 57.73108635 75.84223311

Prediction:[[23.4865289  20.96809788 15.55720467 ... 16.36450231 24.01357493
   1.47605482]
 [24.13522311 23.97819547 25.48396609 ... 22.44928479 23.9458001
  27.30602622]
 [23.94534153 20.96809788 15.55720467 ... 16.36450231 23.93566881
  18.37009533]
 ...
 [24.11963601 20.96809788 23.45606104 ... 24.32152556 23.93007913
  24.81790678]
 [24.08609246 20.96809788 25.51721043 ... 24.08749546 23.86824334
  16.588718  ]
 [24.12470889 20.96809788 27.41878697 ... 27.1298867  24.01357493
  20.56777281]], M(SLOPE):[-3.57390094  3.55486895 -4.6435276   1.49512996 -3.92843344  6.52738738
 -3.59930525  2.26149307 -3.58633188 -4.43138244 -5.19936328  2.98701596
 -6.8432778 ], B(Y-INTERCEPT):[22.74545978 22.74545978 22.74545978 22.74545978 22.74545978 22.74545978
 22.74545978 22.74545978 22.74545978 22.74545978 22.74545978 22.74545978
 22.74545978], COST:[71.99172254 72.12739748 63.20212617 82.52909585 69.3318964  42.15765086
 71.80949192 79.65015336 71.90271396 65.12732788 57.7310863  75.84223306


Prediction:[[23.48654878 20.96811564 15.55721784 ... 16.36451617 24.01359526
   1.47605607]
 [24.13524355 23.97821578 25.48398767 ... 22.4493038  23.94582038
  27.30604934]
 [23.94536181 20.96811564 15.55721784 ... 16.36451617 23.93568908
  18.37011089]
 ...
 [24.11965643 20.96811564 23.4560809  ... 24.32154615 23.9300994
  24.8179278 ]
 [24.08611286 20.96811564 25.51723204 ... 24.08751586 23.86826354
  16.58873204]
 [24.12472931 20.96811564 27.41881018 ... 27.12990967 24.01359526
  20.56779023]], M(SLOPE):[-3.57390379  3.55487178 -4.64353129  1.49513115 -3.92843657  6.52739257
 -3.59930811  2.26149487 -3.58633474 -4.43138596 -5.19936742  2.98701834
 -6.84328325], B(Y-INTERCEPT):[22.74547788 22.74547788 22.74547788 22.74547788 22.74547788 22.74547788
 22.74547788 22.74547788 22.74547788 22.74547788 22.74547788 22.74547788
 22.74547788], COST:[71.99172254 72.12739748 63.20212617 82.52909585 69.3318964  42.15765086
 71.80949192 79.65015336 71.90271396 65.12732788 57.7310863  75.84223306


Prediction:[[23.48655106 20.96811767 15.55721935 ... 16.36451775 24.01359759
   1.47605621]
 [24.13524589 23.9782181  25.48399014 ... 22.44930598 23.9458227
  27.30605199]
 [23.94536413 20.96811767 15.55721935 ... 16.36451775 23.9356914
  18.37011267]
 ...
 [24.11965877 20.96811767 23.45608318 ... 24.32154851 23.93010172
  24.81793021]
 [24.0861152  20.96811767 25.51723452 ... 24.08751819 23.86826586
  16.58873365]
 [24.12473166 20.96811767 27.41881285 ... 27.12991231 24.01359759
  20.56779222]], M(SLOPE):[-3.57390412  3.55487211 -4.64353172  1.49513129 -3.92843693  6.52739317
 -3.59930844  2.26149508 -3.58633507 -4.43138637 -5.1993679   2.98701861
 -6.84328387], B(Y-INTERCEPT):[22.74547996 22.74547996 22.74547996 22.74547996 22.74547996 22.74547996
 22.74547996 22.74547996 22.74547996 22.74547996 22.74547996 22.74547996
 22.74547996], COST:[71.99172254 72.12739748 63.20212617 82.52909585 69.3318964  42.15765086
 71.80949192 79.65015336 71.90271396 65.12732788 57.7310863  75.84223306
 

Prediction:[[23.48655132 20.9681179  15.55721952 ... 16.36451793 24.01359786
   1.47605623]
 [24.13524615 23.97821837 25.48399042 ... 22.44930623 23.94582296
  27.30605229]
 [23.9453644  20.9681179  15.55721952 ... 16.36451793 23.93569166
  18.37011287]
 ...
 [24.11965904 20.9681179  23.45608344 ... 24.32154878 23.93010198
  24.81793048]
 [24.08611546 20.9681179  25.5172348  ... 24.08751846 23.86826612
  16.58873383]
 [24.12473192 20.9681179  27.41881315 ... 27.1299126  24.01359786
  20.56779245]], M(SLOPE):[-3.57390415  3.55487214 -4.64353176  1.4951313  -3.92843697  6.52739324
 -3.59930848  2.2614951  -3.5863351  -4.43138641 -5.19936795  2.98701864
 -6.84328395], B(Y-INTERCEPT):[22.74548019 22.74548019 22.74548019 22.74548019 22.74548019 22.74548019
 22.74548019 22.74548019 22.74548019 22.74548019 22.74548019 22.74548019
 22.74548019], COST:[71.99172254 72.12739748 63.20212617 82.52909585 69.3318964  42.15765086
 71.80949192 79.65015336 71.90271396 65.12732788 57.7310863  75.84223306

 37.93397817]
Prediction:[[23.48655135 20.96811793 15.55721954 ... 16.36451796 24.01359789
   1.47605623]
 [24.13524619 23.9782184  25.48399045 ... 22.44930626 23.945823
  27.30605233]
 [23.94536443 20.96811793 15.55721954 ... 16.36451796 23.9356917
  18.3701129 ]
 ...
 [24.11965907 20.96811793 23.45608347 ... 24.32154881 23.93010201
  24.81793051]
 [24.08611549 20.96811793 25.51723483 ... 24.08751849 23.86826616
  16.58873386]
 [24.12473195 20.96811793 27.41881318 ... 27.12991264 24.01359789
  20.56779248]], M(SLOPE):[-3.57390416  3.55487215 -4.64353177  1.4951313  -3.92843698  6.52739325
 -3.59930848  2.2614951  -3.58633511 -4.43138642 -5.19936796  2.98701865
 -6.84328395], B(Y-INTERCEPT):[22.74548022 22.74548022 22.74548022 22.74548022 22.74548022 22.74548022
 22.74548022 22.74548022 22.74548022 22.74548022 22.74548022 22.74548022
 22.74548022], COST:[71.99172254 72.12739748 63.20212617 82.52909585 69.3318964  42.15765086
 71.80949192 79.65015336 71.90271396 65.12732788 57.7310863  

Prediction:[[23.48655136 20.96811794 15.55721954 ... 16.36451796 24.0135979
   1.47605623]
 [24.13524619 23.9782184  25.48399046 ... 22.44930626 23.945823
  27.30605233]
 [23.94536444 20.96811794 15.55721954 ... 16.36451796 23.9356917
  18.3701129 ]
 ...
 [24.11965908 20.96811794 23.45608348 ... 24.32154882 23.93010202
  24.81793052]
 [24.0861155  20.96811794 25.51723484 ... 24.0875185  23.86826616
  16.58873386]
 [24.12473196 20.96811794 27.41881319 ... 27.12991265 24.0135979
  20.56779248]], M(SLOPE):[-3.57390416  3.55487215 -4.64353177  1.4951313  -3.92843698  6.52739325
 -3.59930848  2.2614951  -3.58633511 -4.43138642 -5.19936796  2.98701865
 -6.84328396], B(Y-INTERCEPT):[22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023], COST:[71.99172254 72.12739748 63.20212617 82.52909585 69.3318964  42.15765086
 71.80949192 79.65015336 71.90271396 65.12732788 57.7310863  75.84223306
 37.

 37.93397817]
Prediction:[[23.48655136 20.96811794 15.55721955 ... 16.36451796 24.0135979
   1.47605623]
 [24.13524619 23.97821841 25.48399046 ... 22.44930626 23.945823
  27.30605233]
 [23.94536444 20.96811794 15.55721955 ... 16.36451796 23.9356917
  18.3701129 ]
 ...
 [24.11965908 20.96811794 23.45608348 ... 24.32154882 23.93010202
  24.81793052]
 [24.0861155  20.96811794 25.51723484 ... 24.0875185  23.86826616
  16.58873386]
 [24.12473196 20.96811794 27.41881319 ... 27.12991265 24.0135979
  20.56779248]], M(SLOPE):[-3.57390416  3.55487215 -4.64353177  1.4951313  -3.92843698  6.52739325
 -3.59930848  2.26149511 -3.58633511 -4.43138642 -5.19936796  2.98701865
 -6.84328396], B(Y-INTERCEPT):[22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023], COST:[71.99172254 72.12739748 63.20212617 82.52909585 69.3318964  42.15765086
 71.80949192 79.65015336 71.90271396 65.12732788 57.7310863  75

 37.93397817]
Prediction:[[23.48655136 20.96811794 15.55721955 ... 16.36451796 24.0135979
   1.47605623]
 [24.13524619 23.97821841 25.48399046 ... 22.44930626 23.945823
  27.30605233]
 [23.94536444 20.96811794 15.55721955 ... 16.36451796 23.9356917
  18.3701129 ]
 ...
 [24.11965908 20.96811794 23.45608348 ... 24.32154882 23.93010202
  24.81793052]
 [24.0861155  20.96811794 25.51723484 ... 24.0875185  23.86826616
  16.58873386]
 [24.12473196 20.96811794 27.41881319 ... 27.12991265 24.0135979
  20.56779248]], M(SLOPE):[-3.57390416  3.55487215 -4.64353177  1.4951313  -3.92843698  6.52739325
 -3.59930848  2.26149511 -3.58633511 -4.43138642 -5.19936796  2.98701865
 -6.84328396], B(Y-INTERCEPT):[22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023], COST:[71.99172254 72.12739748 63.20212617 82.52909585 69.3318964  42.15765086
 71.80949192 79.65015336 71.90271396 65.12732788 57.7310863  75

Prediction:[[23.48655136 20.96811794 15.55721955 ... 16.36451796 24.0135979
   1.47605623]
 [24.13524619 23.97821841 25.48399046 ... 22.44930626 23.945823
  27.30605233]
 [23.94536444 20.96811794 15.55721955 ... 16.36451796 23.9356917
  18.3701129 ]
 ...
 [24.11965908 20.96811794 23.45608348 ... 24.32154882 23.93010202
  24.81793052]
 [24.0861155  20.96811794 25.51723484 ... 24.0875185  23.86826616
  16.58873386]
 [24.12473196 20.96811794 27.41881319 ... 27.12991265 24.0135979
  20.56779248]], M(SLOPE):[-3.57390416  3.55487215 -4.64353177  1.4951313  -3.92843698  6.52739325
 -3.59930848  2.26149511 -3.58633511 -4.43138642 -5.19936796  2.98701865
 -6.84328396], B(Y-INTERCEPT):[22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023], COST:[71.99172254 72.12739748 63.20212617 82.52909585 69.3318964  42.15765086
 71.80949192 79.65015336 71.90271396 65.12732788 57.7310863  75.84223306
 37.

Prediction:[[23.48655136 20.96811794 15.55721955 ... 16.36451796 24.0135979
   1.47605623]
 [24.13524619 23.97821841 25.48399046 ... 22.44930626 23.945823
  27.30605233]
 [23.94536444 20.96811794 15.55721955 ... 16.36451796 23.9356917
  18.3701129 ]
 ...
 [24.11965908 20.96811794 23.45608348 ... 24.32154882 23.93010202
  24.81793052]
 [24.0861155  20.96811794 25.51723484 ... 24.0875185  23.86826616
  16.58873386]
 [24.12473196 20.96811794 27.41881319 ... 27.12991265 24.0135979
  20.56779248]], M(SLOPE):[-3.57390416  3.55487215 -4.64353177  1.4951313  -3.92843698  6.52739325
 -3.59930848  2.26149511 -3.58633511 -4.43138642 -5.19936796  2.98701865
 -6.84328396], B(Y-INTERCEPT):[22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023], COST:[71.99172254 72.12739748 63.20212617 82.52909585 69.3318964  42.15765086
 71.80949192 79.65015336 71.90271396 65.12732788 57.7310863  75.84223306
 37.

Prediction:[[23.48655136 20.96811794 15.55721955 ... 16.36451796 24.0135979
   1.47605623]
 [24.13524619 23.97821841 25.48399046 ... 22.44930626 23.945823
  27.30605233]
 [23.94536444 20.96811794 15.55721955 ... 16.36451796 23.9356917
  18.3701129 ]
 ...
 [24.11965908 20.96811794 23.45608348 ... 24.32154882 23.93010202
  24.81793052]
 [24.0861155  20.96811794 25.51723484 ... 24.0875185  23.86826616
  16.58873386]
 [24.12473196 20.96811794 27.41881319 ... 27.12991265 24.0135979
  20.56779248]], M(SLOPE):[-3.57390416  3.55487215 -4.64353177  1.4951313  -3.92843698  6.52739325
 -3.59930848  2.26149511 -3.58633511 -4.43138642 -5.19936796  2.98701865
 -6.84328396], B(Y-INTERCEPT):[22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023], COST:[71.99172254 72.12739748 63.20212617 82.52909585 69.3318964  42.15765086
 71.80949192 79.65015336 71.90271396 65.12732788 57.7310863  75.84223306
 37.

Prediction:[[23.48655136 20.96811794 15.55721955 ... 16.36451796 24.0135979
   1.47605623]
 [24.13524619 23.97821841 25.48399046 ... 22.44930626 23.945823
  27.30605233]
 [23.94536444 20.96811794 15.55721955 ... 16.36451796 23.9356917
  18.3701129 ]
 ...
 [24.11965908 20.96811794 23.45608348 ... 24.32154882 23.93010202
  24.81793052]
 [24.0861155  20.96811794 25.51723484 ... 24.0875185  23.86826616
  16.58873386]
 [24.12473196 20.96811794 27.41881319 ... 27.12991265 24.0135979
  20.56779248]], M(SLOPE):[-3.57390416  3.55487215 -4.64353177  1.4951313  -3.92843698  6.52739325
 -3.59930848  2.26149511 -3.58633511 -4.43138642 -5.19936796  2.98701865
 -6.84328396], B(Y-INTERCEPT):[22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023], COST:[71.99172254 72.12739748 63.20212617 82.52909585 69.3318964  42.15765086
 71.80949192 79.65015336 71.90271396 65.12732788 57.7310863  75.84223306
 37.

Prediction:[[23.48655136 20.96811794 15.55721955 ... 16.36451796 24.0135979
   1.47605623]
 [24.13524619 23.97821841 25.48399046 ... 22.44930626 23.945823
  27.30605233]
 [23.94536444 20.96811794 15.55721955 ... 16.36451796 23.9356917
  18.3701129 ]
 ...
 [24.11965908 20.96811794 23.45608348 ... 24.32154882 23.93010202
  24.81793052]
 [24.0861155  20.96811794 25.51723484 ... 24.0875185  23.86826616
  16.58873386]
 [24.12473196 20.96811794 27.41881319 ... 27.12991265 24.0135979
  20.56779248]], M(SLOPE):[-3.57390416  3.55487215 -4.64353177  1.4951313  -3.92843698  6.52739325
 -3.59930848  2.26149511 -3.58633511 -4.43138642 -5.19936796  2.98701865
 -6.84328396], B(Y-INTERCEPT):[22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023], COST:[71.99172254 72.12739748 63.20212617 82.52909585 69.3318964  42.15765086
 71.80949192 79.65015336 71.90271396 65.12732788 57.7310863  75.84223306
 37.

Prediction:[[23.48655136 20.96811794 15.55721955 ... 16.36451796 24.0135979
   1.47605623]
 [24.13524619 23.97821841 25.48399046 ... 22.44930626 23.945823
  27.30605233]
 [23.94536444 20.96811794 15.55721955 ... 16.36451796 23.9356917
  18.3701129 ]
 ...
 [24.11965908 20.96811794 23.45608348 ... 24.32154882 23.93010202
  24.81793052]
 [24.0861155  20.96811794 25.51723484 ... 24.0875185  23.86826616
  16.58873386]
 [24.12473196 20.96811794 27.41881319 ... 27.12991265 24.0135979
  20.56779248]], M(SLOPE):[-3.57390416  3.55487215 -4.64353177  1.4951313  -3.92843698  6.52739325
 -3.59930848  2.26149511 -3.58633511 -4.43138642 -5.19936796  2.98701865
 -6.84328396], B(Y-INTERCEPT):[22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023], COST:[71.99172254 72.12739748 63.20212617 82.52909585 69.3318964  42.15765086
 71.80949192 79.65015336 71.90271396 65.12732788 57.7310863  75.84223306
 37.

Prediction:[[23.48655136 20.96811794 15.55721955 ... 16.36451796 24.0135979
   1.47605623]
 [24.13524619 23.97821841 25.48399046 ... 22.44930626 23.945823
  27.30605233]
 [23.94536444 20.96811794 15.55721955 ... 16.36451796 23.9356917
  18.3701129 ]
 ...
 [24.11965908 20.96811794 23.45608348 ... 24.32154882 23.93010202
  24.81793052]
 [24.0861155  20.96811794 25.51723484 ... 24.0875185  23.86826616
  16.58873386]
 [24.12473196 20.96811794 27.41881319 ... 27.12991265 24.0135979
  20.56779248]], M(SLOPE):[-3.57390416  3.55487215 -4.64353177  1.4951313  -3.92843698  6.52739325
 -3.59930848  2.26149511 -3.58633511 -4.43138642 -5.19936796  2.98701865
 -6.84328396], B(Y-INTERCEPT):[22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023], COST:[71.99172254 72.12739748 63.20212617 82.52909585 69.3318964  42.15765086
 71.80949192 79.65015336 71.90271396 65.12732788 57.7310863  75.84223306
 37.

Prediction:[[23.48655136 20.96811794 15.55721955 ... 16.36451796 24.0135979
   1.47605623]
 [24.13524619 23.97821841 25.48399046 ... 22.44930626 23.945823
  27.30605233]
 [23.94536444 20.96811794 15.55721955 ... 16.36451796 23.9356917
  18.3701129 ]
 ...
 [24.11965908 20.96811794 23.45608348 ... 24.32154882 23.93010202
  24.81793052]
 [24.0861155  20.96811794 25.51723484 ... 24.0875185  23.86826616
  16.58873386]
 [24.12473196 20.96811794 27.41881319 ... 27.12991265 24.0135979
  20.56779248]], M(SLOPE):[-3.57390416  3.55487215 -4.64353177  1.4951313  -3.92843698  6.52739325
 -3.59930848  2.26149511 -3.58633511 -4.43138642 -5.19936796  2.98701865
 -6.84328396], B(Y-INTERCEPT):[22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023], COST:[71.99172254 72.12739748 63.20212617 82.52909585 69.3318964  42.15765086
 71.80949192 79.65015336 71.90271396 65.12732788 57.7310863  75.84223306
 37.

Prediction:[[23.48655136 20.96811794 15.55721955 ... 16.36451796 24.0135979
   1.47605623]
 [24.13524619 23.97821841 25.48399046 ... 22.44930626 23.945823
  27.30605233]
 [23.94536444 20.96811794 15.55721955 ... 16.36451796 23.9356917
  18.3701129 ]
 ...
 [24.11965908 20.96811794 23.45608348 ... 24.32154882 23.93010202
  24.81793052]
 [24.0861155  20.96811794 25.51723484 ... 24.0875185  23.86826616
  16.58873386]
 [24.12473196 20.96811794 27.41881319 ... 27.12991265 24.0135979
  20.56779248]], M(SLOPE):[-3.57390416  3.55487215 -4.64353177  1.4951313  -3.92843698  6.52739325
 -3.59930848  2.26149511 -3.58633511 -4.43138642 -5.19936796  2.98701865
 -6.84328396], B(Y-INTERCEPT):[22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023], COST:[71.99172254 72.12739748 63.20212617 82.52909585 69.3318964  42.15765086
 71.80949192 79.65015336 71.90271396 65.12732788 57.7310863  75.84223306
 37.

Prediction:[[23.48655136 20.96811794 15.55721955 ... 16.36451796 24.0135979
   1.47605623]
 [24.13524619 23.97821841 25.48399046 ... 22.44930626 23.945823
  27.30605233]
 [23.94536444 20.96811794 15.55721955 ... 16.36451796 23.9356917
  18.3701129 ]
 ...
 [24.11965908 20.96811794 23.45608348 ... 24.32154882 23.93010202
  24.81793052]
 [24.0861155  20.96811794 25.51723484 ... 24.0875185  23.86826616
  16.58873386]
 [24.12473196 20.96811794 27.41881319 ... 27.12991265 24.0135979
  20.56779248]], M(SLOPE):[-3.57390416  3.55487215 -4.64353177  1.4951313  -3.92843698  6.52739325
 -3.59930848  2.26149511 -3.58633511 -4.43138642 -5.19936796  2.98701865
 -6.84328396], B(Y-INTERCEPT):[22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023], COST:[71.99172254 72.12739748 63.20212617 82.52909585 69.3318964  42.15765086
 71.80949192 79.65015336 71.90271396 65.12732788 57.7310863  75.84223306
 37.

Prediction:[[23.48655136 20.96811794 15.55721955 ... 16.36451796 24.0135979
   1.47605623]
 [24.13524619 23.97821841 25.48399046 ... 22.44930626 23.945823
  27.30605233]
 [23.94536444 20.96811794 15.55721955 ... 16.36451796 23.9356917
  18.3701129 ]
 ...
 [24.11965908 20.96811794 23.45608348 ... 24.32154882 23.93010202
  24.81793052]
 [24.0861155  20.96811794 25.51723484 ... 24.0875185  23.86826616
  16.58873386]
 [24.12473196 20.96811794 27.41881319 ... 27.12991265 24.0135979
  20.56779248]], M(SLOPE):[-3.57390416  3.55487215 -4.64353177  1.4951313  -3.92843698  6.52739325
 -3.59930848  2.26149511 -3.58633511 -4.43138642 -5.19936796  2.98701865
 -6.84328396], B(Y-INTERCEPT):[22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023], COST:[71.99172254 72.12739748 63.20212617 82.52909585 69.3318964  42.15765086
 71.80949192 79.65015336 71.90271396 65.12732788 57.7310863  75.84223306
 37.

Prediction:[[23.48655136 20.96811794 15.55721955 ... 16.36451796 24.0135979
   1.47605623]
 [24.13524619 23.97821841 25.48399046 ... 22.44930626 23.945823
  27.30605233]
 [23.94536444 20.96811794 15.55721955 ... 16.36451796 23.9356917
  18.3701129 ]
 ...
 [24.11965908 20.96811794 23.45608348 ... 24.32154882 23.93010202
  24.81793052]
 [24.0861155  20.96811794 25.51723484 ... 24.0875185  23.86826616
  16.58873386]
 [24.12473196 20.96811794 27.41881319 ... 27.12991265 24.0135979
  20.56779248]], M(SLOPE):[-3.57390416  3.55487215 -4.64353177  1.4951313  -3.92843698  6.52739325
 -3.59930848  2.26149511 -3.58633511 -4.43138642 -5.19936796  2.98701865
 -6.84328396], B(Y-INTERCEPT):[22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023], COST:[71.99172254 72.12739748 63.20212617 82.52909585 69.3318964  42.15765086
 71.80949192 79.65015336 71.90271396 65.12732788 57.7310863  75.84223306
 37.

Prediction:[[23.48655136 20.96811794 15.55721955 ... 16.36451796 24.0135979
   1.47605623]
 [24.13524619 23.97821841 25.48399046 ... 22.44930626 23.945823
  27.30605233]
 [23.94536444 20.96811794 15.55721955 ... 16.36451796 23.9356917
  18.3701129 ]
 ...
 [24.11965908 20.96811794 23.45608348 ... 24.32154882 23.93010202
  24.81793052]
 [24.0861155  20.96811794 25.51723484 ... 24.0875185  23.86826616
  16.58873386]
 [24.12473196 20.96811794 27.41881319 ... 27.12991265 24.0135979
  20.56779248]], M(SLOPE):[-3.57390416  3.55487215 -4.64353177  1.4951313  -3.92843698  6.52739325
 -3.59930848  2.26149511 -3.58633511 -4.43138642 -5.19936796  2.98701865
 -6.84328396], B(Y-INTERCEPT):[22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023], COST:[71.99172254 72.12739748 63.20212617 82.52909585 69.3318964  42.15765086
 71.80949192 79.65015336 71.90271396 65.12732788 57.7310863  75.84223306
 37.

Prediction:[[23.48655136 20.96811794 15.55721955 ... 16.36451796 24.0135979
   1.47605623]
 [24.13524619 23.97821841 25.48399046 ... 22.44930626 23.945823
  27.30605233]
 [23.94536444 20.96811794 15.55721955 ... 16.36451796 23.9356917
  18.3701129 ]
 ...
 [24.11965908 20.96811794 23.45608348 ... 24.32154882 23.93010202
  24.81793052]
 [24.0861155  20.96811794 25.51723484 ... 24.0875185  23.86826616
  16.58873386]
 [24.12473196 20.96811794 27.41881319 ... 27.12991265 24.0135979
  20.56779248]], M(SLOPE):[-3.57390416  3.55487215 -4.64353177  1.4951313  -3.92843698  6.52739325
 -3.59930848  2.26149511 -3.58633511 -4.43138642 -5.19936796  2.98701865
 -6.84328396], B(Y-INTERCEPT):[22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023], COST:[71.99172254 72.12739748 63.20212617 82.52909585 69.3318964  42.15765086
 71.80949192 79.65015336 71.90271396 65.12732788 57.7310863  75.84223306
 37.

Prediction:[[23.48655136 20.96811794 15.55721955 ... 16.36451796 24.0135979
   1.47605623]
 [24.13524619 23.97821841 25.48399046 ... 22.44930626 23.945823
  27.30605233]
 [23.94536444 20.96811794 15.55721955 ... 16.36451796 23.9356917
  18.3701129 ]
 ...
 [24.11965908 20.96811794 23.45608348 ... 24.32154882 23.93010202
  24.81793052]
 [24.0861155  20.96811794 25.51723484 ... 24.0875185  23.86826616
  16.58873386]
 [24.12473196 20.96811794 27.41881319 ... 27.12991265 24.0135979
  20.56779248]], M(SLOPE):[-3.57390416  3.55487215 -4.64353177  1.4951313  -3.92843698  6.52739325
 -3.59930848  2.26149511 -3.58633511 -4.43138642 -5.19936796  2.98701865
 -6.84328396], B(Y-INTERCEPT):[22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023], COST:[71.99172254 72.12739748 63.20212617 82.52909585 69.3318964  42.15765086
 71.80949192 79.65015336 71.90271396 65.12732788 57.7310863  75.84223306
 37.

Prediction:[[23.48655136 20.96811794 15.55721955 ... 16.36451796 24.0135979
   1.47605623]
 [24.13524619 23.97821841 25.48399046 ... 22.44930626 23.945823
  27.30605233]
 [23.94536444 20.96811794 15.55721955 ... 16.36451796 23.9356917
  18.3701129 ]
 ...
 [24.11965908 20.96811794 23.45608348 ... 24.32154882 23.93010202
  24.81793052]
 [24.0861155  20.96811794 25.51723484 ... 24.0875185  23.86826616
  16.58873386]
 [24.12473196 20.96811794 27.41881319 ... 27.12991265 24.0135979
  20.56779248]], M(SLOPE):[-3.57390416  3.55487215 -4.64353177  1.4951313  -3.92843698  6.52739325
 -3.59930848  2.26149511 -3.58633511 -4.43138642 -5.19936796  2.98701865
 -6.84328396], B(Y-INTERCEPT):[22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023], COST:[71.99172254 72.12739748 63.20212617 82.52909585 69.3318964  42.15765086
 71.80949192 79.65015336 71.90271396 65.12732788 57.7310863  75.84223306
 37.

Prediction:[[23.48655136 20.96811794 15.55721955 ... 16.36451796 24.0135979
   1.47605623]
 [24.13524619 23.97821841 25.48399046 ... 22.44930626 23.945823
  27.30605233]
 [23.94536444 20.96811794 15.55721955 ... 16.36451796 23.9356917
  18.3701129 ]
 ...
 [24.11965908 20.96811794 23.45608348 ... 24.32154882 23.93010202
  24.81793052]
 [24.0861155  20.96811794 25.51723484 ... 24.0875185  23.86826616
  16.58873386]
 [24.12473196 20.96811794 27.41881319 ... 27.12991265 24.0135979
  20.56779248]], M(SLOPE):[-3.57390416  3.55487215 -4.64353177  1.4951313  -3.92843698  6.52739325
 -3.59930848  2.26149511 -3.58633511 -4.43138642 -5.19936796  2.98701865
 -6.84328396], B(Y-INTERCEPT):[22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023], COST:[71.99172254 72.12739748 63.20212617 82.52909585 69.3318964  42.15765086
 71.80949192 79.65015336 71.90271396 65.12732788 57.7310863  75.84223306
 37.

Prediction:[[23.48655136 20.96811794 15.55721955 ... 16.36451796 24.0135979
   1.47605623]
 [24.13524619 23.97821841 25.48399046 ... 22.44930626 23.945823
  27.30605233]
 [23.94536444 20.96811794 15.55721955 ... 16.36451796 23.9356917
  18.3701129 ]
 ...
 [24.11965908 20.96811794 23.45608348 ... 24.32154882 23.93010202
  24.81793052]
 [24.0861155  20.96811794 25.51723484 ... 24.0875185  23.86826616
  16.58873386]
 [24.12473196 20.96811794 27.41881319 ... 27.12991265 24.0135979
  20.56779248]], M(SLOPE):[-3.57390416  3.55487215 -4.64353177  1.4951313  -3.92843698  6.52739325
 -3.59930848  2.26149511 -3.58633511 -4.43138642 -5.19936796  2.98701865
 -6.84328396], B(Y-INTERCEPT):[22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023], COST:[71.99172254 72.12739748 63.20212617 82.52909585 69.3318964  42.15765086
 71.80949192 79.65015336 71.90271396 65.12732788 57.7310863  75.84223306
 37.

Prediction:[[23.48655136 20.96811794 15.55721955 ... 16.36451796 24.0135979
   1.47605623]
 [24.13524619 23.97821841 25.48399046 ... 22.44930626 23.945823
  27.30605233]
 [23.94536444 20.96811794 15.55721955 ... 16.36451796 23.9356917
  18.3701129 ]
 ...
 [24.11965908 20.96811794 23.45608348 ... 24.32154882 23.93010202
  24.81793052]
 [24.0861155  20.96811794 25.51723484 ... 24.0875185  23.86826616
  16.58873386]
 [24.12473196 20.96811794 27.41881319 ... 27.12991265 24.0135979
  20.56779248]], M(SLOPE):[-3.57390416  3.55487215 -4.64353177  1.4951313  -3.92843698  6.52739325
 -3.59930848  2.26149511 -3.58633511 -4.43138642 -5.19936796  2.98701865
 -6.84328396], B(Y-INTERCEPT):[22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023], COST:[71.99172254 72.12739748 63.20212617 82.52909585 69.3318964  42.15765086
 71.80949192 79.65015336 71.90271396 65.12732788 57.7310863  75.84223306
 37.

Prediction:[[23.48655136 20.96811794 15.55721955 ... 16.36451796 24.0135979
   1.47605623]
 [24.13524619 23.97821841 25.48399046 ... 22.44930626 23.945823
  27.30605233]
 [23.94536444 20.96811794 15.55721955 ... 16.36451796 23.9356917
  18.3701129 ]
 ...
 [24.11965908 20.96811794 23.45608348 ... 24.32154882 23.93010202
  24.81793052]
 [24.0861155  20.96811794 25.51723484 ... 24.0875185  23.86826616
  16.58873386]
 [24.12473196 20.96811794 27.41881319 ... 27.12991265 24.0135979
  20.56779248]], M(SLOPE):[-3.57390416  3.55487215 -4.64353177  1.4951313  -3.92843698  6.52739325
 -3.59930848  2.26149511 -3.58633511 -4.43138642 -5.19936796  2.98701865
 -6.84328396], B(Y-INTERCEPT):[22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023], COST:[71.99172254 72.12739748 63.20212617 82.52909585 69.3318964  42.15765086
 71.80949192 79.65015336 71.90271396 65.12732788 57.7310863  75.84223306
 37.

Prediction:[[23.48655136 20.96811794 15.55721955 ... 16.36451796 24.0135979
   1.47605623]
 [24.13524619 23.97821841 25.48399046 ... 22.44930626 23.945823
  27.30605233]
 [23.94536444 20.96811794 15.55721955 ... 16.36451796 23.9356917
  18.3701129 ]
 ...
 [24.11965908 20.96811794 23.45608348 ... 24.32154882 23.93010202
  24.81793052]
 [24.0861155  20.96811794 25.51723484 ... 24.0875185  23.86826616
  16.58873386]
 [24.12473196 20.96811794 27.41881319 ... 27.12991265 24.0135979
  20.56779248]], M(SLOPE):[-3.57390416  3.55487215 -4.64353177  1.4951313  -3.92843698  6.52739325
 -3.59930848  2.26149511 -3.58633511 -4.43138642 -5.19936796  2.98701865
 -6.84328396], B(Y-INTERCEPT):[22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023], COST:[71.99172254 72.12739748 63.20212617 82.52909585 69.3318964  42.15765086
 71.80949192 79.65015336 71.90271396 65.12732788 57.7310863  75.84223306
 37.

Prediction:[[23.48655136 20.96811794 15.55721955 ... 16.36451796 24.0135979
   1.47605623]
 [24.13524619 23.97821841 25.48399046 ... 22.44930626 23.945823
  27.30605233]
 [23.94536444 20.96811794 15.55721955 ... 16.36451796 23.9356917
  18.3701129 ]
 ...
 [24.11965908 20.96811794 23.45608348 ... 24.32154882 23.93010202
  24.81793052]
 [24.0861155  20.96811794 25.51723484 ... 24.0875185  23.86826616
  16.58873386]
 [24.12473196 20.96811794 27.41881319 ... 27.12991265 24.0135979
  20.56779248]], M(SLOPE):[-3.57390416  3.55487215 -4.64353177  1.4951313  -3.92843698  6.52739325
 -3.59930848  2.26149511 -3.58633511 -4.43138642 -5.19936796  2.98701865
 -6.84328396], B(Y-INTERCEPT):[22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023], COST:[71.99172254 72.12739748 63.20212617 82.52909585 69.3318964  42.15765086
 71.80949192 79.65015336 71.90271396 65.12732788 57.7310863  75.84223306
 37.

Prediction:[[23.48655136 20.96811794 15.55721955 ... 16.36451796 24.0135979
   1.47605623]
 [24.13524619 23.97821841 25.48399046 ... 22.44930626 23.945823
  27.30605233]
 [23.94536444 20.96811794 15.55721955 ... 16.36451796 23.9356917
  18.3701129 ]
 ...
 [24.11965908 20.96811794 23.45608348 ... 24.32154882 23.93010202
  24.81793052]
 [24.0861155  20.96811794 25.51723484 ... 24.0875185  23.86826616
  16.58873386]
 [24.12473196 20.96811794 27.41881319 ... 27.12991265 24.0135979
  20.56779248]], M(SLOPE):[-3.57390416  3.55487215 -4.64353177  1.4951313  -3.92843698  6.52739325
 -3.59930848  2.26149511 -3.58633511 -4.43138642 -5.19936796  2.98701865
 -6.84328396], B(Y-INTERCEPT):[22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023], COST:[71.99172254 72.12739748 63.20212617 82.52909585 69.3318964  42.15765086
 71.80949192 79.65015336 71.90271396 65.12732788 57.7310863  75.84223306
 37.

 37.93397817]
Prediction:[[23.48655136 20.96811794 15.55721955 ... 16.36451796 24.0135979
   1.47605623]
 [24.13524619 23.97821841 25.48399046 ... 22.44930626 23.945823
  27.30605233]
 [23.94536444 20.96811794 15.55721955 ... 16.36451796 23.9356917
  18.3701129 ]
 ...
 [24.11965908 20.96811794 23.45608348 ... 24.32154882 23.93010202
  24.81793052]
 [24.0861155  20.96811794 25.51723484 ... 24.0875185  23.86826616
  16.58873386]
 [24.12473196 20.96811794 27.41881319 ... 27.12991265 24.0135979
  20.56779248]], M(SLOPE):[-3.57390416  3.55487215 -4.64353177  1.4951313  -3.92843698  6.52739325
 -3.59930848  2.26149511 -3.58633511 -4.43138642 -5.19936796  2.98701865
 -6.84328396], B(Y-INTERCEPT):[22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023], COST:[71.99172254 72.12739748 63.20212617 82.52909585 69.3318964  42.15765086
 71.80949192 79.65015336 71.90271396 65.12732788 57.7310863  75

Prediction:[[23.48655136 20.96811794 15.55721955 ... 16.36451796 24.0135979
   1.47605623]
 [24.13524619 23.97821841 25.48399046 ... 22.44930626 23.945823
  27.30605233]
 [23.94536444 20.96811794 15.55721955 ... 16.36451796 23.9356917
  18.3701129 ]
 ...
 [24.11965908 20.96811794 23.45608348 ... 24.32154882 23.93010202
  24.81793052]
 [24.0861155  20.96811794 25.51723484 ... 24.0875185  23.86826616
  16.58873386]
 [24.12473196 20.96811794 27.41881319 ... 27.12991265 24.0135979
  20.56779248]], M(SLOPE):[-3.57390416  3.55487215 -4.64353177  1.4951313  -3.92843698  6.52739325
 -3.59930848  2.26149511 -3.58633511 -4.43138642 -5.19936796  2.98701865
 -6.84328396], B(Y-INTERCEPT):[22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023], COST:[71.99172254 72.12739748 63.20212617 82.52909585 69.3318964  42.15765086
 71.80949192 79.65015336 71.90271396 65.12732788 57.7310863  75.84223306
 37.

Prediction:[[23.48655136 20.96811794 15.55721955 ... 16.36451796 24.0135979
   1.47605623]
 [24.13524619 23.97821841 25.48399046 ... 22.44930626 23.945823
  27.30605233]
 [23.94536444 20.96811794 15.55721955 ... 16.36451796 23.9356917
  18.3701129 ]
 ...
 [24.11965908 20.96811794 23.45608348 ... 24.32154882 23.93010202
  24.81793052]
 [24.0861155  20.96811794 25.51723484 ... 24.0875185  23.86826616
  16.58873386]
 [24.12473196 20.96811794 27.41881319 ... 27.12991265 24.0135979
  20.56779248]], M(SLOPE):[-3.57390416  3.55487215 -4.64353177  1.4951313  -3.92843698  6.52739325
 -3.59930848  2.26149511 -3.58633511 -4.43138642 -5.19936796  2.98701865
 -6.84328396], B(Y-INTERCEPT):[22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023], COST:[71.99172254 72.12739748 63.20212617 82.52909585 69.3318964  42.15765086
 71.80949192 79.65015336 71.90271396 65.12732788 57.7310863  75.84223306
 37.

Prediction:[[23.48655136 20.96811794 15.55721955 ... 16.36451796 24.0135979
   1.47605623]
 [24.13524619 23.97821841 25.48399046 ... 22.44930626 23.945823
  27.30605233]
 [23.94536444 20.96811794 15.55721955 ... 16.36451796 23.9356917
  18.3701129 ]
 ...
 [24.11965908 20.96811794 23.45608348 ... 24.32154882 23.93010202
  24.81793052]
 [24.0861155  20.96811794 25.51723484 ... 24.0875185  23.86826616
  16.58873386]
 [24.12473196 20.96811794 27.41881319 ... 27.12991265 24.0135979
  20.56779248]], M(SLOPE):[-3.57390416  3.55487215 -4.64353177  1.4951313  -3.92843698  6.52739325
 -3.59930848  2.26149511 -3.58633511 -4.43138642 -5.19936796  2.98701865
 -6.84328396], B(Y-INTERCEPT):[22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023], COST:[71.99172254 72.12739748 63.20212617 82.52909585 69.3318964  42.15765086
 71.80949192 79.65015336 71.90271396 65.12732788 57.7310863  75.84223306
 37.

Prediction:[[23.48655136 20.96811794 15.55721955 ... 16.36451796 24.0135979
   1.47605623]
 [24.13524619 23.97821841 25.48399046 ... 22.44930626 23.945823
  27.30605233]
 [23.94536444 20.96811794 15.55721955 ... 16.36451796 23.9356917
  18.3701129 ]
 ...
 [24.11965908 20.96811794 23.45608348 ... 24.32154882 23.93010202
  24.81793052]
 [24.0861155  20.96811794 25.51723484 ... 24.0875185  23.86826616
  16.58873386]
 [24.12473196 20.96811794 27.41881319 ... 27.12991265 24.0135979
  20.56779248]], M(SLOPE):[-3.57390416  3.55487215 -4.64353177  1.4951313  -3.92843698  6.52739325
 -3.59930848  2.26149511 -3.58633511 -4.43138642 -5.19936796  2.98701865
 -6.84328396], B(Y-INTERCEPT):[22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023], COST:[71.99172254 72.12739748 63.20212617 82.52909585 69.3318964  42.15765086
 71.80949192 79.65015336 71.90271396 65.12732788 57.7310863  75.84223306
 37.

Prediction:[[23.48655136 20.96811794 15.55721955 ... 16.36451796 24.0135979
   1.47605623]
 [24.13524619 23.97821841 25.48399046 ... 22.44930626 23.945823
  27.30605233]
 [23.94536444 20.96811794 15.55721955 ... 16.36451796 23.9356917
  18.3701129 ]
 ...
 [24.11965908 20.96811794 23.45608348 ... 24.32154882 23.93010202
  24.81793052]
 [24.0861155  20.96811794 25.51723484 ... 24.0875185  23.86826616
  16.58873386]
 [24.12473196 20.96811794 27.41881319 ... 27.12991265 24.0135979
  20.56779248]], M(SLOPE):[-3.57390416  3.55487215 -4.64353177  1.4951313  -3.92843698  6.52739325
 -3.59930848  2.26149511 -3.58633511 -4.43138642 -5.19936796  2.98701865
 -6.84328396], B(Y-INTERCEPT):[22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023], COST:[71.99172254 72.12739748 63.20212617 82.52909585 69.3318964  42.15765086
 71.80949192 79.65015336 71.90271396 65.12732788 57.7310863  75.84223306
 37.

Prediction:[[23.48655136 20.96811794 15.55721955 ... 16.36451796 24.0135979
   1.47605623]
 [24.13524619 23.97821841 25.48399046 ... 22.44930626 23.945823
  27.30605233]
 [23.94536444 20.96811794 15.55721955 ... 16.36451796 23.9356917
  18.3701129 ]
 ...
 [24.11965908 20.96811794 23.45608348 ... 24.32154882 23.93010202
  24.81793052]
 [24.0861155  20.96811794 25.51723484 ... 24.0875185  23.86826616
  16.58873386]
 [24.12473196 20.96811794 27.41881319 ... 27.12991265 24.0135979
  20.56779248]], M(SLOPE):[-3.57390416  3.55487215 -4.64353177  1.4951313  -3.92843698  6.52739325
 -3.59930848  2.26149511 -3.58633511 -4.43138642 -5.19936796  2.98701865
 -6.84328396], B(Y-INTERCEPT):[22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023], COST:[71.99172254 72.12739748 63.20212617 82.52909585 69.3318964  42.15765086
 71.80949192 79.65015336 71.90271396 65.12732788 57.7310863  75.84223306
 37.

Prediction:[[23.48655136 20.96811794 15.55721955 ... 16.36451796 24.0135979
   1.47605623]
 [24.13524619 23.97821841 25.48399046 ... 22.44930626 23.945823
  27.30605233]
 [23.94536444 20.96811794 15.55721955 ... 16.36451796 23.9356917
  18.3701129 ]
 ...
 [24.11965908 20.96811794 23.45608348 ... 24.32154882 23.93010202
  24.81793052]
 [24.0861155  20.96811794 25.51723484 ... 24.0875185  23.86826616
  16.58873386]
 [24.12473196 20.96811794 27.41881319 ... 27.12991265 24.0135979
  20.56779248]], M(SLOPE):[-3.57390416  3.55487215 -4.64353177  1.4951313  -3.92843698  6.52739325
 -3.59930848  2.26149511 -3.58633511 -4.43138642 -5.19936796  2.98701865
 -6.84328396], B(Y-INTERCEPT):[22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023], COST:[71.99172254 72.12739748 63.20212617 82.52909585 69.3318964  42.15765086
 71.80949192 79.65015336 71.90271396 65.12732788 57.7310863  75.84223306
 37.

Prediction:[[23.48655136 20.96811794 15.55721955 ... 16.36451796 24.0135979
   1.47605623]
 [24.13524619 23.97821841 25.48399046 ... 22.44930626 23.945823
  27.30605233]
 [23.94536444 20.96811794 15.55721955 ... 16.36451796 23.9356917
  18.3701129 ]
 ...
 [24.11965908 20.96811794 23.45608348 ... 24.32154882 23.93010202
  24.81793052]
 [24.0861155  20.96811794 25.51723484 ... 24.0875185  23.86826616
  16.58873386]
 [24.12473196 20.96811794 27.41881319 ... 27.12991265 24.0135979
  20.56779248]], M(SLOPE):[-3.57390416  3.55487215 -4.64353177  1.4951313  -3.92843698  6.52739325
 -3.59930848  2.26149511 -3.58633511 -4.43138642 -5.19936796  2.98701865
 -6.84328396], B(Y-INTERCEPT):[22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023], COST:[71.99172254 72.12739748 63.20212617 82.52909585 69.3318964  42.15765086
 71.80949192 79.65015336 71.90271396 65.12732788 57.7310863  75.84223306
 37.

Prediction:[[23.48655136 20.96811794 15.55721955 ... 16.36451796 24.0135979
   1.47605623]
 [24.13524619 23.97821841 25.48399046 ... 22.44930626 23.945823
  27.30605233]
 [23.94536444 20.96811794 15.55721955 ... 16.36451796 23.9356917
  18.3701129 ]
 ...
 [24.11965908 20.96811794 23.45608348 ... 24.32154882 23.93010202
  24.81793052]
 [24.0861155  20.96811794 25.51723484 ... 24.0875185  23.86826616
  16.58873386]
 [24.12473196 20.96811794 27.41881319 ... 27.12991265 24.0135979
  20.56779248]], M(SLOPE):[-3.57390416  3.55487215 -4.64353177  1.4951313  -3.92843698  6.52739325
 -3.59930848  2.26149511 -3.58633511 -4.43138642 -5.19936796  2.98701865
 -6.84328396], B(Y-INTERCEPT):[22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023], COST:[71.99172254 72.12739748 63.20212617 82.52909585 69.3318964  42.15765086
 71.80949192 79.65015336 71.90271396 65.12732788 57.7310863  75.84223306
 37.

Prediction:[[23.48655136 20.96811794 15.55721955 ... 16.36451796 24.0135979
   1.47605623]
 [24.13524619 23.97821841 25.48399046 ... 22.44930626 23.945823
  27.30605233]
 [23.94536444 20.96811794 15.55721955 ... 16.36451796 23.9356917
  18.3701129 ]
 ...
 [24.11965908 20.96811794 23.45608348 ... 24.32154882 23.93010202
  24.81793052]
 [24.0861155  20.96811794 25.51723484 ... 24.0875185  23.86826616
  16.58873386]
 [24.12473196 20.96811794 27.41881319 ... 27.12991265 24.0135979
  20.56779248]], M(SLOPE):[-3.57390416  3.55487215 -4.64353177  1.4951313  -3.92843698  6.52739325
 -3.59930848  2.26149511 -3.58633511 -4.43138642 -5.19936796  2.98701865
 -6.84328396], B(Y-INTERCEPT):[22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023], COST:[71.99172254 72.12739748 63.20212617 82.52909585 69.3318964  42.15765086
 71.80949192 79.65015336 71.90271396 65.12732788 57.7310863  75.84223306
 37.

Prediction:[[23.48655136 20.96811794 15.55721955 ... 16.36451796 24.0135979
   1.47605623]
 [24.13524619 23.97821841 25.48399046 ... 22.44930626 23.945823
  27.30605233]
 [23.94536444 20.96811794 15.55721955 ... 16.36451796 23.9356917
  18.3701129 ]
 ...
 [24.11965908 20.96811794 23.45608348 ... 24.32154882 23.93010202
  24.81793052]
 [24.0861155  20.96811794 25.51723484 ... 24.0875185  23.86826616
  16.58873386]
 [24.12473196 20.96811794 27.41881319 ... 27.12991265 24.0135979
  20.56779248]], M(SLOPE):[-3.57390416  3.55487215 -4.64353177  1.4951313  -3.92843698  6.52739325
 -3.59930848  2.26149511 -3.58633511 -4.43138642 -5.19936796  2.98701865
 -6.84328396], B(Y-INTERCEPT):[22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023], COST:[71.99172254 72.12739748 63.20212617 82.52909585 69.3318964  42.15765086
 71.80949192 79.65015336 71.90271396 65.12732788 57.7310863  75.84223306
 37.

Prediction:[[23.48655136 20.96811794 15.55721955 ... 16.36451796 24.0135979
   1.47605623]
 [24.13524619 23.97821841 25.48399046 ... 22.44930626 23.945823
  27.30605233]
 [23.94536444 20.96811794 15.55721955 ... 16.36451796 23.9356917
  18.3701129 ]
 ...
 [24.11965908 20.96811794 23.45608348 ... 24.32154882 23.93010202
  24.81793052]
 [24.0861155  20.96811794 25.51723484 ... 24.0875185  23.86826616
  16.58873386]
 [24.12473196 20.96811794 27.41881319 ... 27.12991265 24.0135979
  20.56779248]], M(SLOPE):[-3.57390416  3.55487215 -4.64353177  1.4951313  -3.92843698  6.52739325
 -3.59930848  2.26149511 -3.58633511 -4.43138642 -5.19936796  2.98701865
 -6.84328396], B(Y-INTERCEPT):[22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023], COST:[71.99172254 72.12739748 63.20212617 82.52909585 69.3318964  42.15765086
 71.80949192 79.65015336 71.90271396 65.12732788 57.7310863  75.84223306
 37.

Prediction:[[23.48655136 20.96811794 15.55721955 ... 16.36451796 24.0135979
   1.47605623]
 [24.13524619 23.97821841 25.48399046 ... 22.44930626 23.945823
  27.30605233]
 [23.94536444 20.96811794 15.55721955 ... 16.36451796 23.9356917
  18.3701129 ]
 ...
 [24.11965908 20.96811794 23.45608348 ... 24.32154882 23.93010202
  24.81793052]
 [24.0861155  20.96811794 25.51723484 ... 24.0875185  23.86826616
  16.58873386]
 [24.12473196 20.96811794 27.41881319 ... 27.12991265 24.0135979
  20.56779248]], M(SLOPE):[-3.57390416  3.55487215 -4.64353177  1.4951313  -3.92843698  6.52739325
 -3.59930848  2.26149511 -3.58633511 -4.43138642 -5.19936796  2.98701865
 -6.84328396], B(Y-INTERCEPT):[22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023], COST:[71.99172254 72.12739748 63.20212617 82.52909585 69.3318964  42.15765086
 71.80949192 79.65015336 71.90271396 65.12732788 57.7310863  75.84223306
 37.

Prediction:[[23.48655136 20.96811794 15.55721955 ... 16.36451796 24.0135979
   1.47605623]
 [24.13524619 23.97821841 25.48399046 ... 22.44930626 23.945823
  27.30605233]
 [23.94536444 20.96811794 15.55721955 ... 16.36451796 23.9356917
  18.3701129 ]
 ...
 [24.11965908 20.96811794 23.45608348 ... 24.32154882 23.93010202
  24.81793052]
 [24.0861155  20.96811794 25.51723484 ... 24.0875185  23.86826616
  16.58873386]
 [24.12473196 20.96811794 27.41881319 ... 27.12991265 24.0135979
  20.56779248]], M(SLOPE):[-3.57390416  3.55487215 -4.64353177  1.4951313  -3.92843698  6.52739325
 -3.59930848  2.26149511 -3.58633511 -4.43138642 -5.19936796  2.98701865
 -6.84328396], B(Y-INTERCEPT):[22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023], COST:[71.99172254 72.12739748 63.20212617 82.52909585 69.3318964  42.15765086
 71.80949192 79.65015336 71.90271396 65.12732788 57.7310863  75.84223306
 37.

Prediction:[[23.48655136 20.96811794 15.55721955 ... 16.36451796 24.0135979
   1.47605623]
 [24.13524619 23.97821841 25.48399046 ... 22.44930626 23.945823
  27.30605233]
 [23.94536444 20.96811794 15.55721955 ... 16.36451796 23.9356917
  18.3701129 ]
 ...
 [24.11965908 20.96811794 23.45608348 ... 24.32154882 23.93010202
  24.81793052]
 [24.0861155  20.96811794 25.51723484 ... 24.0875185  23.86826616
  16.58873386]
 [24.12473196 20.96811794 27.41881319 ... 27.12991265 24.0135979
  20.56779248]], M(SLOPE):[-3.57390416  3.55487215 -4.64353177  1.4951313  -3.92843698  6.52739325
 -3.59930848  2.26149511 -3.58633511 -4.43138642 -5.19936796  2.98701865
 -6.84328396], B(Y-INTERCEPT):[22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023], COST:[71.99172254 72.12739748 63.20212617 82.52909585 69.3318964  42.15765086
 71.80949192 79.65015336 71.90271396 65.12732788 57.7310863  75.84223306
 37.

Prediction:[[23.48655136 20.96811794 15.55721955 ... 16.36451796 24.0135979
   1.47605623]
 [24.13524619 23.97821841 25.48399046 ... 22.44930626 23.945823
  27.30605233]
 [23.94536444 20.96811794 15.55721955 ... 16.36451796 23.9356917
  18.3701129 ]
 ...
 [24.11965908 20.96811794 23.45608348 ... 24.32154882 23.93010202
  24.81793052]
 [24.0861155  20.96811794 25.51723484 ... 24.0875185  23.86826616
  16.58873386]
 [24.12473196 20.96811794 27.41881319 ... 27.12991265 24.0135979
  20.56779248]], M(SLOPE):[-3.57390416  3.55487215 -4.64353177  1.4951313  -3.92843698  6.52739325
 -3.59930848  2.26149511 -3.58633511 -4.43138642 -5.19936796  2.98701865
 -6.84328396], B(Y-INTERCEPT):[22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023 22.74548023
 22.74548023], COST:[71.99172254 72.12739748 63.20212617 82.52909585 69.3318964  42.15765086
 71.80949192 79.65015336 71.90271396 65.12732788 57.7310863  75.84223306
 37.

In [ ]:
sgd.intercept_

In [ ]:
y_train[2]

In [ ]:
X_train[20]

In [12]:
from sklearn.linear_model import SGDRegressor

sgd = SGDRegressor()

sgd.fit(X_train, y_train)

E:\Anaconda\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


SGDRegressor()

In [13]:
sgd.predict(X_train)

array([ 4.48544418, 28.27499019, 17.34872303, 29.82196674, 19.63534227,
       15.85856118, 17.96293722, 12.50508034,  8.95650931, 19.12092106,
       34.40390306, 32.9463705 , 23.44894024, 19.5787917 , 22.80605919,
       26.72790813, 21.56718123, 16.6673031 , 32.31045795, 10.39046183,
       19.16739808, 32.67570573, 18.70920421, 15.66375725, 18.76780122,
       14.54323107, 24.63257606, 23.79967344, 16.54774603, 13.64226281,
       20.01343598, 24.82533171, 17.3305354 , 25.05497421, 22.28376046,
       27.81871625, 36.06631784, 16.79357899, 12.09865098, 34.82186603,
       31.27757269, 20.48716122, 39.81108665, 28.8300502 , 29.08797735,
       17.3072777 , 26.98230186, 40.31356607, 28.48126209, 16.80811346,
       37.50191934, 35.71662379, 13.79095015, 28.8884103 , 21.61361781,
       24.46975747, 21.2576459 , 23.72847496, 27.87793054, 29.76305784,
       14.43401562, 25.95736941, 23.10472989, 12.97407501, 13.98359238,
       25.750279  , 19.0273982 , 30.67538086, 10.55653504, 23.59

In [27]:
y_train

array([[14.4],
       [24.4],
       [18.1],
       [22.5],
       [20.5],
       [15.2],
       [17.4],
       [13.6],
       [ 8.7],
       [18.2],
       [35.4],
       [31.7],
       [33. ],
       [22.2],
       [20.4],
       [23.9],
       [25. ],
       [12.7],
       [29.1],
       [12. ],
       [17.7],
       [27. ],
       [20.6],
       [10.2],
       [17.5],
       [19.7],
       [29.8],
       [20.5],
       [14.9],
       [10.9],
       [19.5],
       [22.7],
       [19.5],
       [24.6],
       [25. ],
       [24.5],
       [50. ],
       [14.3],
       [11.8],
       [31. ],
       [28.7],
       [16.2],
       [43.5],
       [25. ],
       [22. ],
       [19.9],
       [22.1],
       [46. ],
       [22.9],
       [20.2],
       [43.1],
       [34.6],
       [13.8],
       [24.3],
       [21.5],
       [24.4],
       [21.2],
       [23.8],
       [26.6],
       [25.1],
       [ 9.6],
       [19.4],
       [19.4],
       [ 9.5],
       [14. ],
       [26.5],
       [13

In [15]:
sgd.intercept_

array([22.75667823])

In [16]:
sgd.coef_

array([-0.98487197,  0.974604  , -0.17518778,  0.65694864, -1.78058236,
        2.78869206, -0.3516023 , -3.01188196,  1.4837457 , -1.26147507,
       -2.25658518,  0.58716905, -3.43242698])

In [ ]:
sgd.theta_