In [40]:
import pandas as pd
import numpy as np

df = pd.read_csv('E:/DS_and_ML/datasets/weight-height.csv')

df['Gender_labels'] = df['Gender'].astype('category').cat.codes

In [41]:
df = df.drop('Gender', axis = 1)

In [42]:
df.head(5)

Height      Weight  Gender_labels
0  73.847017  241.893563              1
1  68.781904  162.310473              1
2  74.110105  212.740856              1
3  71.730978  220.042470              1
4  69.881796  206.349801              1

In [43]:
from sklearn.model_selection import train_test_split

X = df.drop('Height', axis=1)
y = df['Height']

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state = 42)

In [58]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
y_train = np.array(y_train)

y_train = y_train.reshape(-1,1)

y_train

array([[63.48570167],
       [71.17286856],
       [62.02116348],
       ...,
       [64.3254058 ],
       [69.07449203],
       [67.58883983]])

In [111]:
def Gradient_Descent(X,y):
    m = b = 0
    iteration = 200
    learning_rate = 0.02
    n = len(X)
    
    
    for i in range(iteration):
        y_pred = m * X + b
        cost = (1/n)*sum([val**2 for val in (y-y_pred)])
        md = -(2/n) * sum(X*(y - y_pred))
        bd = -(2/n) * sum(y - y_pred)
        m = m - learning_rate * md
        b = b - learning_rate * bd
        
        print("M:{}, B:{}, COST:{}, Predicitons:{}".format(m[0], b[0], cost[0], y_pred[0]))

Gradient_Descent(X_train, y_train)

M:0.14212539458887566, B:2.6528105109165, COST:4413.160829124425, Predicitons:[0. 0.]
M:0.2785657733941963, B:5.199508601396339, COST:4067.3382706282387, Predicitons:[2.51089943 2.54825323]
M:0.409548537047304, B:7.644338768256988, COST:3748.6282007181476, Predicitons:[4.92136287 4.99457633]
M:0.5352919901542876, B:9.991375728443208, COST:3454.905000289013, Predicitons:[7.23540779 7.3430465 ]
M:0.656005705136992, B:12.244531210221972, COST:3184.209698773518, Predicitons:[9.4568909  9.59757787]
M:0.7718908715203888, B:14.407560472729603, COST:2934.7369088968285, Predicitons:[11.58951469 11.76192799]
M:0.8831406312484495, B:16.484068564736926, COST:2704.822785746486, Predicitons:[13.63683353 13.8397041 ]
M:0.9899404005873875, B:18.477516333063942, COST:2492.93392985114, Predicitons:[15.60225961 15.83436916]
M:1.0924681791527684, B:20.391226190657886, COST:2297.6571602579543, Predicitons:[17.48906865 17.74924762]
M:1.1908948465755338, B:22.228387653948076, COST:2117.6900894009027, Predici

M:3.4229436832115616, B:63.89020770964733, COST:8.584716076861962, Predicitons:[60.37658961 61.27479174]
M:3.4281513304719753, B:63.98740991217794, COST:8.080924843601625, Predicitons:[60.47242545 61.3720533 ]
M:3.433150671841972, B:64.08072402660731, COST:7.616630843028877, Predicitons:[60.56442786 61.4654244 ]
M:3.4379500395571694, B:64.17030557645953, COST:7.1887374921011045, Predicitons:[60.65275017 61.55506065]
M:3.4425574325637585, B:64.25630386431764, COST:6.794390979886031, Predicitons:[60.73753959 61.64111146]
M:3.446980529850084, B:64.33886222066144, COST:6.430961234228605, Predicitons:[60.81893743 61.72372023]
M:3.4512267032449566, B:64.41811824275148, COST:6.096024380630727, Predicitons:[60.89707936 61.80302465]
M:3.455303029704034, B:64.49420402395792, COST:5.787346576354966, Predicitons:[60.97209561 61.87915689]
M:3.4592163031047485, B:64.5672463739161, COST:5.502869111934398, Predicitons:[61.04411121 61.95224384]
M:3.4629730455694343, B:64.63736702987596, COST:5.24069468

M:3.548165736406228, B:66.22751259364976, COST:2.1681686959436695, Predicitons:[62.68103925 63.6135239 ]
M:3.5483645015388547, B:66.23122260082027, COST:2.167434777347341, Predicitons:[62.6846971  63.61723617]
M:3.5485553160661767, B:66.23478420770397, COST:2.1667583979689735, Predicitons:[62.68820865 63.62079996]
M:3.5487384980124057, B:66.2382033503123, COST:2.166135046733855, Predicitons:[62.69157973 63.62422119]
M:3.5489143526807854, B:66.24148572721631, COST:2.16556056623558, Predicitons:[62.69481596 63.62750557]
M:3.5490831731624297, B:66.24463680904417, COST:2.1650311250083694, Predicitons:[62.69792275 63.63065857]
M:3.5492452408248085, B:66.2476618475989, COST:2.164543191973364, Predicitons:[62.70090527 63.63368546]
M:3.549400825780692, B:66.25056588461145, COST:2.1640935128883103, Predicitons:[62.70376848 63.63659127]
M:3.5495501873383404, B:66.25335376014348, COST:2.1636790886435193, Predicitons:[62.70651717 63.63938085]
M:3.549693574433683, B:66.25603012065424, COST:2.163297

In [97]:
X = scaler.fit_transform(X)
y = np.array(y)

y = y.reshape(-1,1)
X_b = np.c_[np.ones((10000,1)), X]

In [99]:
# mx + b 
theta_best = np.linalg.inv(X_b.T.dot(X_b)).dot(X_b.T).dot(y)

In [100]:
theta_best

array([[66.36755975],
       [ 3.94141617],
       [-0.48143213]])

In [101]:
y_predict = X_b.dot(theta_best)

In [102]:
y_predict

array([[75.76251635],
       [65.99294252],
       [72.18374695],
       ...,
       [62.80222302],
       [67.14510043],
       [60.98216538]])

In [106]:
from sklearn.metrics import mean_squared_error

mse = mean_squared_error(y_predict, y)

print("MSE:", mse)

MSE: 2.059057879331962


In [149]:
def SGD(X,y):
    m,b = np.random.rand(2,1)
    iteration = 300
    learning_rate = 0.1
    n = len(X)
    
    for i in range(iteration):
        y_pred = m * X + b
        cost = (1/n)*sum([val**2 for val in (y-y_pred)])
        md = -(2/n) * sum(X*(y - y_pred))
        bd = -(2/n) * sum(y - y_pred)
        m = m - learning_rate * md
        b = b - learning_rate * bd
        
        
    #plt.scatter(m_arr, b_arr)
        
    
        
        print("M:{}, B:{}, iter:{}, cost:{} pred:{}".format(m,b,i,cost, y_pred[0]))

In [150]:
SGD(X_train, y_train)

M:[1.27783897 1.09555453], B:[13.54354155 13.54354155], iter:0, cost:[4362.40767339 4363.7000974 ] pred:[-0.35858463 -0.35219765]
M:[1.73289815 1.40478616], B:[24.0988858 24.0988858], iter:1, cost:[2792.71808167 2795.57783679] pred:[12.26762942 12.45950802]
M:[2.09694549 1.65217146], B:[32.54316119 32.54316119], iter:2, cost:[1788.11674296 1791.97959   ] pred:[22.36860067 22.70887256]
M:[2.38818337 1.8500797 ], B:[39.29858151 39.29858151], iter:3, cost:[1145.17188619 1149.67671205] pred:[30.44937766 30.90836419]
M:[2.62117367 2.00840629], B:[44.70291776 44.70291776], iter:4, cost:[733.68717786 738.60287017] pred:[36.91399926 37.4679575 ]
M:[2.80756591 2.13506757], B:[49.02638676 49.02638676], iter:5, cost:[470.33696453 475.51561136] pred:[42.08569654 42.71563214]
M:[2.9566797  2.23639659], B:[52.48516197 52.48516197], iter:6, cost:[301.79282799 307.13976573] pred:[46.22305436 46.91377186]
M:[3.07597073 2.3174598 ], B:[55.25218213 55.25218213], iter:7, cost:[193.92458061 199.37922452] p

M:[3.55313413 2.64171217], B:[66.32024581 66.32024581], iter:67, cost:[2.15880749 7.80492904] pred:[62.77246536 63.70631013]
M:[3.55313428 2.64171227], B:[66.3202492 66.3202492], iter:68, cost:[2.15880749 7.80492904] pred:[62.77246942 63.70631425]
M:[3.5531344  2.64171235], B:[66.32025192 66.32025192], iter:69, cost:[2.15880749 7.80492904] pred:[62.77247266 63.70631754]
M:[3.55313449 2.64171241], B:[66.32025409 66.32025409], iter:70, cost:[2.15880749 7.80492904] pred:[62.77247526 63.70632018]
M:[3.55313457 2.64171246], B:[66.32025583 66.32025583], iter:71, cost:[2.15880749 7.80492904] pred:[62.77247734 63.70632229]
M:[3.55313463 2.6417125 ], B:[66.32025721 66.32025721], iter:72, cost:[2.15880749 7.80492904] pred:[62.772479   63.70632397]
M:[3.55313467 2.64171254], B:[66.32025833 66.32025833], iter:73, cost:[2.15880749 7.80492904] pred:[62.77248033 63.70632532]
M:[3.55313471 2.64171256], B:[66.32025922 66.32025922], iter:74, cost:[2.15880749 7.80492904] pred:[62.77248139 63.7063264 ]
M:

M:[3.55313486 2.64171267], B:[66.32026277 66.32026277], iter:134, cost:[2.15880749 7.80492904] pred:[62.77248565 63.70633072]
M:[3.55313486 2.64171267], B:[66.32026277 66.32026277], iter:135, cost:[2.15880749 7.80492904] pred:[62.77248565 63.70633072]
M:[3.55313486 2.64171267], B:[66.32026277 66.32026277], iter:136, cost:[2.15880749 7.80492904] pred:[62.77248565 63.70633072]
M:[3.55313486 2.64171267], B:[66.32026277 66.32026277], iter:137, cost:[2.15880749 7.80492904] pred:[62.77248565 63.70633072]
M:[3.55313486 2.64171267], B:[66.32026277 66.32026277], iter:138, cost:[2.15880749 7.80492904] pred:[62.77248565 63.70633072]
M:[3.55313486 2.64171267], B:[66.32026277 66.32026277], iter:139, cost:[2.15880749 7.80492904] pred:[62.77248565 63.70633072]
M:[3.55313486 2.64171267], B:[66.32026277 66.32026277], iter:140, cost:[2.15880749 7.80492904] pred:[62.77248565 63.70633072]
M:[3.55313486 2.64171267], B:[66.32026277 66.32026277], iter:141, cost:[2.15880749 7.80492904] pred:[62.77248565 63.70

M:[3.55313486 2.64171267], B:[66.32026277 66.32026277], iter:199, cost:[2.15880749 7.80492904] pred:[62.77248565 63.70633072]
M:[3.55313486 2.64171267], B:[66.32026277 66.32026277], iter:200, cost:[2.15880749 7.80492904] pred:[62.77248565 63.70633072]
M:[3.55313486 2.64171267], B:[66.32026277 66.32026277], iter:201, cost:[2.15880749 7.80492904] pred:[62.77248565 63.70633072]
M:[3.55313486 2.64171267], B:[66.32026277 66.32026277], iter:202, cost:[2.15880749 7.80492904] pred:[62.77248565 63.70633072]
M:[3.55313486 2.64171267], B:[66.32026277 66.32026277], iter:203, cost:[2.15880749 7.80492904] pred:[62.77248565 63.70633072]
M:[3.55313486 2.64171267], B:[66.32026277 66.32026277], iter:204, cost:[2.15880749 7.80492904] pred:[62.77248565 63.70633072]
M:[3.55313486 2.64171267], B:[66.32026277 66.32026277], iter:205, cost:[2.15880749 7.80492904] pred:[62.77248565 63.70633072]
M:[3.55313486 2.64171267], B:[66.32026277 66.32026277], iter:206, cost:[2.15880749 7.80492904] pred:[62.77248565 63.70

M:[3.55313486 2.64171267], B:[66.32026277 66.32026277], iter:267, cost:[2.15880749 7.80492904] pred:[62.77248565 63.70633072]
M:[3.55313486 2.64171267], B:[66.32026277 66.32026277], iter:268, cost:[2.15880749 7.80492904] pred:[62.77248565 63.70633072]
M:[3.55313486 2.64171267], B:[66.32026277 66.32026277], iter:269, cost:[2.15880749 7.80492904] pred:[62.77248565 63.70633072]
M:[3.55313486 2.64171267], B:[66.32026277 66.32026277], iter:270, cost:[2.15880749 7.80492904] pred:[62.77248565 63.70633072]
M:[3.55313486 2.64171267], B:[66.32026277 66.32026277], iter:271, cost:[2.15880749 7.80492904] pred:[62.77248565 63.70633072]
M:[3.55313486 2.64171267], B:[66.32026277 66.32026277], iter:272, cost:[2.15880749 7.80492904] pred:[62.77248565 63.70633072]
M:[3.55313486 2.64171267], B:[66.32026277 66.32026277], iter:273, cost:[2.15880749 7.80492904] pred:[62.77248565 63.70633072]
M:[3.55313486 2.64171267], B:[66.32026277 66.32026277], iter:274, cost:[2.15880749 7.80492904] pred:[62.77248565 63.70